apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
  namespace: video-app
  labels:
    app: stream-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
        - name: stream-service
          image: tsripan/stream-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: AUTH_SERVICE_URL
            - name: FILE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: FILE_SERVICE_URL
            - name: MYSQL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: MYSQL_SERVICE_URL
            - name: UPLOAD_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: UPLOAD_EXTERNAL_URL
          livenessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: stream-service
  namespace: video-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
spec:
  type: LoadBalancer
  selector:
    app: stream-service
  ports:
    - port: 5004
      targetPort: 5004
