apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: video-app
  labels:
    app: upload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
        - name: upload-service
          image: tsripan/upload-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: AUTH_SERVICE_URL
            - name: FILE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: FILE_SERVICE_URL
            - name: MYSQL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: MYSQL_SERVICE_URL
            - name: STREAM_EXTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: STREAM_EXTERNAL_URL
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: video-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
spec:
  type: LoadBalancer
  selector:
    app: upload-service
  ports:
    - port: 5000
      targetPort: 5000
